FROM node:20-alpine

# Tạo thư mục làm việc trong container
WORKDIR /app

# Sao chép các file cấu hình của npm
COPY package*.json ./

# Cài đặt Angular CLI và các phụ thuộc của dự án
RUN npm install -g @angular/cli && npm install

# Sao chép toàn bộ mã nguồn vào container
COPY . .

# Mở cổng 4200 để truy cập từ bên ngoài container
EXPOSE 4200

# Khởi chạy ứng dụng Angular với host là 0.0.0.0 để lắng nghe tất cả các kết nối
# Thêm --disable-host-check để bỏ qua kiểm tra host header
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--disable-host-check"]
