name: Start Backend and Frontend

on: [push]

jobs:
  Backend_AFF:
    runs-on: [self-hosted, be-aff]
    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v3
        with:
          repository: "TungSyo/BE_AFF"
          path: "BE_AFF"

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: BE_AFF/

      - name: Build Backend
        run: dotnet build --configuration Release
        working-directory: BE_AFF/

      - name: Run Backend
        run: dotnet run --no-build --project BE_AFF/ --urls "http://localhost:5000" &
        
      - name: Wait for Backend to be ready
        run: |
          for i in {1..10}; do
            curl -s http://localhost:5000/health && exit 0
            sleep 5
          done
          exit 1  # Fail nếu backend không chạy

  Frontend_AFF:
    runs-on: [self-hosted, fe-aff]
    needs: Backend_AFF 
    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v3
        with:
          repository: "TungSyo/FE_AFF"
          path: "FE_AFF"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Angular dependencies
        run: npm install
        working-directory: FE_AFF/

      - name: Build Angular app
        run: npm run build --if-present
        working-directory: FE_AFF/

      - name: Start Angular App
        run: npm start --host 0.0.0.0 --port 4200 &
        
      - name: Wait for Frontend to be ready
        run: |
          for i in {1..10}; do
            curl -s http://localhost:4200 && exit 0
            sleep 5
          done
          exit 1  # Fail nếu frontend không chạy
