name: Selenium Test Automation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Selenium_Test_Automation:
    name: Selenium Test Automation
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Cài đặt JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Bước 3: Cài đặt các dependencies cần thiết
      - name: Install dependencies
        run: |
          choco install maven

      # Bước 4: Cài đặt Google Chrome Portable từ file .paf.exe
      - name: Install Google Chrome Portable
        run: |
          # Tải Google Chrome Portable từ GitHub repository
          Invoke-WebRequest -Uri "https://github.com/TungSyo/Aumation_AFF/raw/main/chrome-files/GoogleChromePortable_online.paf.exe" -OutFile "GoogleChromePortable_online.paf.exe"
          # Cài đặt Google Chrome Portable
          Start-Process -FilePath "GoogleChromePortable_online.paf.exe" -ArgumentList "/S" -NoNewWindow -Wait

      # Bước 5: Cài đặt ChromeDriver từ file .exe
      - name: Install ChromeDriver
        run: |
          # Tải ChromeDriver từ GitHub repository
          Invoke-WebRequest -Uri "https://github.com/TungSyo/Aumation_AFF/raw/main/chrome-files/chromedriver.exe" -OutFile "chromedriver.exe"
          # Di chuyển chromedriver.exe vào thư mục hệ thống để Selenium có thể tìm thấy
          Move-Item -Path "chromedriver.exe" -Destination "C:\Windows\System32\chromedriver.exe"

      # Bước 6: Chạy các bài kiểm tra Selenium
      - name: Run Selenium Tests
        run: mvn clean test
